#! /usr/bin/env bash

# TODO: rewrite in Python?

## Where to look for the files 
builddir="."
test -n "$1" && builddir=$1

echo PYTHONPATH=$PYTHONPATH 1>&2

## Get list of all tags excluding tip
declare -a tags
## Test we're in a git repo, and if not, exit
git tag >/dev/null 2>&1 || exit 0
## Get all tags
for t in $(git tag | sort -r); do
  if [[ "$t" == *"alpha"* ]]; then continue; fi
  if [[ "$t" == *"chacal"* ]]; then continue; fi
  tags+=($t);
done
let numtags=${#tags[@]}

## Write out ana files per tag
let N=$numtags-1
for i in `seq 0 $N`; do
    tag=${tags[$i]}

    tagfile="analist-$tag.dat"
    test -e "$builddir/$tagfile" && continue
    echo "Writing analysis list to $builddir/$tagfile" 1>&2

    > $builddir/$tagfile
    git ls-tree --full-tree -r --name-only $tag src/Analysis/ src/Analyses/ analyses/ | grep "\.cc" | \
        while read i; do basename $i .cc >> $tagfile; done
    sort $tagfile > $$ && mv $$ $tagfile
done

## Diff ana lists between all tags
echo "Rivet analysis diffs"
echo "===================="
let numdiffs=$numtags-1
let N=$numdiffs-1
for i in `seq 0 $N`; do
    let j=$i+1
    rev0=${tags[$j]}
    rev1=${tags[$i]}
    echo -e "\n$rev0 -> $rev1"

    tagfile0="analist-$rev0.dat"
    tagfile1="analist-$rev1.dat"

    anas=$(comm -13 $tagfile0 $tagfile1)
    test -n "$(echo $anas)" && { echo -e "\n  Added:"; echo $anas | xargs rivet --list-analyses | while read l; do echo "    $l"; done; }

    anas=$(comm -23 $tagfile0 $tagfile1)
    test -n "$(echo $anas)" && { echo -e "\n  Removed:"; echo $anas | sed -e 's/\ \+/\n/g' | while read l; do echo "    $l"; done; }

    echo
done
