variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2


stages:
- compile
- precheck
- check
- validate
- deploy


.trigger_template: &trigger_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule"'
      #changes:
      #- .gitlab*
      #- configure.ac
      #- Makefile.am
      #- "**/Makefile.am"
      #- m4/*
      #- ci/*
      #- bin/*
      #- include/**/*
      #- src/**/*
      #- pyext/**/*
      #- test/*
      when: always
    - when: never


.build_template: &build_template
  image:
    hepstore/hepbase-$ARCH
  stage: compile
  script:
    - shopt -s expand_aliases
    - set -e
    - BUILD_PREFIX="$CI_PROJECT_DIR"
    - MAKE="make -j $(nproc)"
    #/build_$ARCH"
    - mkdir -p $BUILD_PREFIX
    - INSTALL_PREFIX="$CI_PROJECT_DIR/local_$ARCH"
    - mkdir -p $INSTALL_PREFIX
    - TEST_PREFIX="$CI_PROJECT_DIR/test_$ARCH"
    - mkdir -p $TEST_PREFIX
    ## Build the core library
    # - export CPPFLAGS="$CPPFLAGS -DNDEBUG"
    #- export PATH=$INSTALL_PREFIX/bin:$PATH
    - if [[ "x$COVERAGE" != "x" ]]; then apt-get update && apt-get install -y lcov curl; fi
    ## Build YODA
    - git clone --depth 1 --branch main https://gitlab.com/hepcedar/yoda.git yoda/
    - cd yoda/
    - autoreconf -i
    - ./configure --prefix=$INSTALL_PREFIX
    - $MAKE
    - $MAKE install
    - cp yodaenv.sh $INSTALL_PREFIX/
    - cd ..
    ## Build Rivet
    - autoreconf -i
    - cd $BUILD_PREFIX
    - if [[ "$ALLANAS" != "1" ]]; then ANAOPT="--disable-analyses"; fi
    - CONF="./configure --prefix=$INSTALL_PREFIX $ANAOPT --with-yoda=$INSTALL_PREFIX --with-hepmc=/usr/local --with-fastjet=/usr/local $COVERAGE $EXTRA_CONFIGURE_ARGS"
    - if (echo $ARCH | grep -q hepmc3); then CONF=${CONF/with-hepmc/with-hepmc3}; fi
    - echo $CONF
    - $CONF
    - $MAKE RIVET_BUILD_ALLCAT=1
    # - echo @$LD_LIBRARY_PATH@
    - $MAKE check || (cat test/test-suite.log && false)
    - $MAKE install
    - cp rivetenv.sh $INSTALL_PREFIX/
    ## Basic testing
    - echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
    - echo "PYTHONPATH = $PYTHONPATH"
    - python --version
    - ls /etc/profile.d || true
    - root-config --prefix || true
    - cat $INSTALL_PREFIX/yodaenv.sh
    - source $INSTALL_PREFIX/yodaenv.sh
    - cat $INSTALL_PREFIX/rivetenv.sh
    - source $INSTALL_PREFIX/rivetenv.sh
    - rivet -h
    # - |
    #   if [[ "$ALLANAS" != "1" ]]; then
    #     ./ci/getAffectedRoutines.sh anasToCompile.txt
    #     echo "==== echo analyses to compile ====="
    #     cat anasToCompile.txt
    #     find analyses -name MC_TTBAR.cc >> anasToCompile.txt # need at least one!
    #     cat anasToCompile.txt | sort --unique > anasToCompile.tmp ; mv anasToCompile.tmp anasToCompile.txt
    #     echo rivet-build `cat anasToCompile.txt`
    #     RIVET_BUILD_NOCAT=1 rivet-build RivetModifiedAnas.so `cat anasToCompile.txt`
    #     mkdir -p ${CI_PROJECT_DIR}/local${PYTHON_VERSION}/lib/Rivet/.
    #     mkdir -p ${CI_PROJECT_DIR}/local${PYTHON_VERSION}/share/Rivet/.
    #     cp RivetModifiedAnas.so ${CI_PROJECT_DIR}/local${PYTHON_VERSION}/lib/Rivet/.
    #     while read p ; do cp ${p/%.cc}* ${CI_PROJECT_DIR}/local${PYTHON_VERSION}/share/Rivet/. ; done < anasToCompile.txt
    #     rm ${CI_PROJECT_DIR}/local${PYTHON_VERSION}/share/Rivet/*cc
    #   fi
    # - find $CI_PROJECT_DIR
    # - ls $CI_PROJECT_DIR
    - if [[ "x$COVERAGE" != "x" ]]; then lcov --summary ./test/coverage/coverage.info; fi
    - if [[ "x$COVERAGE" != "x" ]]; then MSG=$(./test/coverage/mkreport); fi
    - MR_ID=$(git ls-remote origin | grep "${CI_COMMIT_SHORT_SHA}.*merge-requests" | grep -o "merge-requests/.*" | cut -d "/" -f 2) || true
    - |
      if [[ "x$COVERAGE" != "x" && "x$MR_ID" != "x" ]]; then
        curl --request POST "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests/${MR_ID}/notes" \
            --header "PRIVATE-TOKEN: ${CI_PRIVATE_TOKEN}" --header "Content-Type: application/json" \
            --data "{ \"body\": \"${MSG}\" }" --silent -o /dev/null
      fi
  coverage: '/^\s*lines\.+: (\d+\.\d+)%/'
  artifacts:
    when: always
    paths:
      # - ${CI_PROJECT_DIR}/local_$ARCH/
      # - ${CI_PROJECT_DIR}/test_$ARCH/
      # - ${CI_PROJECT_DIR}/Make*
      # - ${CI_PROJECT_DIR}/config.log
      - config.log
      - test/
      - local_$ARCH/
      - test_$ARCH/
    expire_in: 36 hrs
  <<: *trigger_template

build_ubuntu_gcc_hepmc3_py3:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
    COVERAGE: --enable-coverage
  <<: *build_template

build_ubuntu_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
    EXTRA_CONFIGURE_ARGS: --with-yaml-cpp
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *build_template

build_ubuntu_clang_hepmc3_py3:
  variables:
    ARCH: ubuntu-clang-hepmc3-py3
  <<: *build_template

build_ubuntu_clang_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-clang-hepmc3-py3
    EXTRA_CONFIGURE_ARGS: --with-yaml-cpp
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *build_template

build_fedora_gcc_hepmc3_py3:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  # rules:
  #   if: $CI_PIPELINE_SOURCE == "schedule"
  <<: *build_template

build_fedora_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
    EXTRA_CONFIGURE_ARGS: --with-yaml-cpp
  before_script:
    - dnf install -y yaml-cpp-devel
  # rules:
  #   if: $CI_PIPELINE_SOURCE == "schedule"
  <<: *build_template

# build_ubuntu_intel_hepmc3_py3:
#   tags: [intel-compat]
#   variables:
#     ARCH: ubuntu-intel-hepmc3-py3
#   rules:
#     if: $CI_PIPELINE_SOURCE == "schedule"
#   <<: *build_template

# TODO: Add MacOSX

sync_coverage:
  stage: deploy
  before_script:
    - git config --global user.name "RivetCheck (CI-bot)"
    - git config --global user.email "rivet-support@cern.ch"
  script:
    - echo "Syncing coverage reference"
    - ref_diff=$(git diff test/coverage/coverage.json)
    - echo $ref_diff
    - |
      if [[ ! -z "${ref_diff}" ]]; then
        git add -f test/coverage/coverage.json
        git commit -m "coverage-reference update [skip ci]"
        git push "https://gitlab-ci-token:${CI_PRIVATE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:$CI_COMMIT_REF_NAME
      fi
  needs:
    - job: build_ubuntu_gcc_hepmc3_py3
  rules:
    - if: '($CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME == "main") && $CI_PIPELINE_SOURCE != "schedule"'

announce:
  stage: deploy
  image:
    python:3-alpine
  script:
    - apk add --no-cache curl jq
    - pip install --upgrade pip --root-user-action=ignore
    - pip install --no-cache-dir atproto Mastodon.py --root-user-action=ignore
    - |
      MR_DATA=$(curl --silent --header "PRIVATE-TOKEN: ${CI_PRIVATE_TOKEN}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/commits/${CI_COMMIT_SHA}/merge_requests")
      MR_COUNT=$(echo "$MR_DATA" | jq '[.[] | select(.state=="merged")] | length')
      if [ "$MR_COUNT" -gt 0 ]; then
        # Extract labels from the first matching merge request
        MR_LABELS=$(echo "$MR_DATA" | jq -r '[.[] | select(.state=="merged")][0].labels | join(", ")')
        if [[ "${MR_LABELS}" == *"#tweetme"* ]]; then
          MR_IID=$(echo "$MR_DATA" | jq -r '[.[] | select(.state=="merged")][0].iid')
          export MR_TITLE=$(echo "$MR_DATA" | jq -r '[.[] | select(.state=="merged")][0].title')
          export MR_URL="${CI_PROJECT_URL}/-/merge_requests/${MR_IID}"
          echo "Triggering announcement."
          python ci/post2socials.py
        else
          echo "Required label not found. Skipping announcement."
        fi
      else
        echo "No open merge request found for commit ${CI_COMMIT_SHA}."
      fi
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'

get_test_hepmc:
  image:
    jgoclawski/wget
  stage: precheck
  script:
    - URL1=https://rivetval.web.cern.ch/rivetval/HEPMC/LHC-13-Top-All.hepmc.gz
    - URL2=https://cgutscho.web.cern.ch/cgutscho/LHC-13-Top-All.hepmc.gz
    - for u in $URL1 $URL2; do wget --no-check-certificate $u -O tt.hepmc.gz && break; done
    -  mkdir -p valhepmc
   # - | #takes up too much space  to be uploaded as an artifact sadly :(
   #   if [[ "$VAL" == "1" ]]; then
   #     URL1=https://rivetval.web.cern.ch/rivetval/HEPMC/
   #     URL2=https://cgutscho.web.cern.ch/cgutscho/
   #     for u in $URL1 $URL2; do wget -q --no-check-certificate $u -O list.txt && break; done
   #     while read p ; do
   #       a=${p#<*href=\"} ; b=${a%\"*}
   #       if echo ${b} | grep gz ; then
   #         echo $b
   #         for u in $URL1 $URL2; do wget -q  --no-check-certificate $u/$b -O valhepmc/$b  && break; done
   #       fi
   #     done < list.txt
   #   fi
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/tt.hepmc.gz
      - $CI_PROJECT_DIR/valhepmc
    expire_in: 36 hrs
  <<: *trigger_template


.check_plugin_template: &check_plugin_template
  image:
    hepstore/hepbase-$ARCH
  stage: check
  script:
    - INSTALL_PREFIX="$CI_PROJECT_DIR/local_$ARCH"
    - TEST_PREFIX="$CI_PROJECT_DIR/test_$ARCH"
    - VAL_PREFIX="$CI_PROJECT_DIR/val_$ARCH"
    - mkdir -p $VAL_PREFIX
    - source $INSTALL_PREFIX/rivetenv.sh
    - cd $TEST_PREFIX
    ## Identify changed routines + a few standard ones for CI tests
    - echo $ALLANAS
    - |
      if [[ "$ALLANAS" != "1" ]]; then
        $CI_PROJECT_DIR/ci/getAffectedRoutines.sh $CI_PROJECT_DIR/anasToCompile.txt
        find $CI_PROJECT_DIR/analyses -name MC_TTBAR.cc  >> $CI_PROJECT_DIR/anasToCompile.txt
        find $CI_PROJECT_DIR/analyses -name ATLAS_2018_I1656578.cc  >> $CI_PROJECT_DIR/anasToCompile.txt
        find $CI_PROJECT_DIR/analyses -name ATLAS_2018_I1646686.cc  >> $CI_PROJECT_DIR/anasToCompile.txt
        find $CI_PROJECT_DIR/analyses -name ATLAS_2017_I1614149.cc  >> $CI_PROJECT_DIR/anasToCompile.txt
        sort --unique $CI_PROJECT_DIR/anasToCompile.txt -o $CI_PROJECT_DIR/anasToCompile.txt
        cat $CI_PROJECT_DIR/anasToCompile.txt
        ## Build changed routines
        rivet-build RivetModifiedAnas.so `cat $CI_PROJECT_DIR/anasToCompile.txt`
        mkdir -p $INSTALL_PREFIX/lib/Rivet
        mkdir -p $INSTALL_PREFIX/share/Rivet
        cp RivetModifiedAnas.so $INSTALL_PREFIX/lib/Rivet/
        cat $CI_PROJECT_DIR/anasToCompile.txt | while read p; do cp ${p/%.cc}* $INSTALL_PREFIX/share/Rivet/; done
      fi
    ## Test analysis loading and listing
    - rivet --list-analyses
    - rivet-mkanalysis MY_TEST
    - rivet-build MY_TEST.cc
    - rivet --pwd --list-analyses
    - ls $CI_PROJECT_DIR
    ## Test standard analyses on a small event sample
    - rivet --pwd -a MC_TTBAR:TTMODE=ANYLEP,ATLAS_2017_I1614149,ATLAS_2018_I1646686,ATLAS_2018_I1656578 -H ttbar_test_run.yoda $CI_PROJECT_DIR/tt.hepmc.gz
    - | #monthly full validation only... SLOW!
      if [[ "$VAL" == "1" ]]; then
        if [[ "$ARCH" == "ubuntu-gcc-hepmc3-py3" ]]; then
          cd $VAL_PREFIX
          export RIVET_RANDOM_SEED=12345
          export RIVET_FORCE_DETERMINISTIC_RANDNORM=1
          rivet-mkvaldir VALDIR --ref-dir $CI_PROJECT_DIR/analyses/valref/
          cd VALDIR
          make check -j $(nproc)
          DIFFDIRS=`find . -name '*.diffdir' -print`
          if [ -z "$DIFFDIRS" ]; then
            echo "No differences found: SUCCESS."
          else
            echo "Differences found:"; echo "$DIFFDIRS"; exit 1
          fi
        fi
      fi
  artifacts:
    when: always
    paths:
      - local_$ARCH/
      - test_$ARCH/
      - val_$ARCH/VALDIR/Make*
      - val_$ARCH/VALDIR/*.yoda
      - val_$ARCH/VALDIR/*.html
      - val_$ARCH/VALDIR/*.diff
      - val_$ARCH/VALDIR/tmp/*.log
      - val_$ARCH/VALDIR/*_*_*/*.*
    #exclude:
    #  - test_$ARCH/VALDIR/*/*.gz
    expire_in: 36 hrs
  <<: *trigger_template

check_plugin_ubuntu_gcc_hepmc3_py3:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  needs: [build_ubuntu_gcc_hepmc3_py3, get_test_hepmc]
  <<: *check_plugin_template

check_plugin_ubuntu_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  needs: [build_ubuntu_gcc_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *check_plugin_template

check_plugin_ubuntu_clang_hepmc3_py3:
  variables:
    ARCH: ubuntu-clang-hepmc3-py3
  needs: [build_ubuntu_clang_hepmc3_py3, get_test_hepmc]
  <<: *check_plugin_template

check_plugin_ubuntu_clang_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-clang-hepmc3-py3
  needs: [build_ubuntu_clang_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *check_plugin_template

check_plugin_fedora_gcc_hepmc3_py3:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  # rules:
  #   if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [build_fedora_gcc_hepmc3_py3, get_test_hepmc]
  <<: *check_plugin_template

check_plugin_fedora_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  # rules:
  #   if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [build_fedora_gcc_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - dnf install -y yaml-cpp-devel
  <<: *check_plugin_template

# check_plugin_ubuntu_intel_hepmc3_py3:
#   tags: [intel-compat]
#   variables:
#     ARCH: ubuntu-intel-hepmc3-py3
#   rules:
#     if: $CI_PIPELINE_SOURCE == "schedule"
#   needs: [build_ubuntu_intel_hepmc3_py3, get_test_hepmc]
#   <<: *check_plugin_template


.make_plots_template: &make_plots_template
  image:
    hepstore/hepbase-$ARCH-latex
  stage: validate
  script:
    - INSTALL_PREFIX="$CI_PROJECT_DIR/local_$ARCH"
    - TEST_PREFIX="$CI_PROJECT_DIR/test_$ARCH"
    - source $INSTALL_PREFIX/yodaenv.sh
    - source $INSTALL_PREFIX/rivetenv.sh
    - cd $TEST_PREFIX
    - ls /usr/local/lib64
    - echo $LD_LIBRARY_PATH
    - ls
    - rivet-mkhtml --verbose -o ttbar_test_plots ttbar_test_run.yoda
  artifacts:
    when: always
    paths:
      - test_$ARCH/ttbar_test_plots/
    expire_in: 36 hrs
  <<: *trigger_template

make_plots_ubuntu_gcc_hepmc3_py3:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  rules:
    if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [check_plugin_ubuntu_gcc_hepmc3_py3]
  <<: *make_plots_template

make_plots_ubuntu_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  rules:
    if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [check_plugin_ubuntu_gcc_hepmc3_py3_yaml_cpp]
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *make_plots_template

make_plots_ubuntu_clang_hepmc3_py3:
  variables:
    ARCH: ubuntu-clang-hepmc3-py3
  rules:
    if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [check_plugin_ubuntu_clang_hepmc3_py3]
  <<: *make_plots_template

make_plots_ubuntu_clang_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-clang-hepmc3-py3
  rules:
    if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [check_plugin_ubuntu_clang_hepmc3_py3_yaml_cpp]
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *make_plots_template

make_plots_fedora_gcc_hepmc3_py3:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  rules:
    if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [check_plugin_fedora_gcc_hepmc3_py3]
  <<: *make_plots_template

make_plots_fedora_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  rules:
    if: $CI_PIPELINE_SOURCE == "schedule"
  needs: [check_plugin_fedora_gcc_hepmc3_py3_yaml_cpp]
  before_script:
    - dnf install -y yaml-cpp-devel 
  <<: *make_plots_template

# make_plots_ubuntu_intel_hepmc3_py3:
#   tags: [intel-compat]
#   variables:
#     ARCH: ubuntu-intel-hepmc3-py3
#   rules:
#     if: $CI_PIPELINE_SOURCE == "schedule"
#   needs: [check_plugin_ubuntu_intel_hepmc3_py3]
#   <<: *make_plots_template


.check_lwtnn_analyses_template: &check_lwtnn_analyses_template
  image: hepstore/hepbase-$ARCH
  stage: check
  script:
  # If we're not in val mode, don't do this test:
    - if [[ $VAL != 1 ]]; then exit 0; fi
  # LWTNN setup variables
    - LWTNN_INSTALL_PREFIX="$CI_PROJECT_DIR"
    - LWTNN_VERSION="2.13"
  # general building/compilation variables
    - MAKE="make -j $(nproc)"
    - INSTALL_PREFIX="$CI_PROJECT_DIR/local_$ARCH"
  # install and build lwtnn
    - wget https://github.com/lwtnn/lwtnn/archive/refs/tags/v$LWTNN_VERSION.tar.gz
    - tar -xf v$LWTNN_VERSION.tar.gz
    - cd lwtnn-$LWTNN_VERSION
    - mkdir -p build && cd build
    - cmake -DBUILTIN_BOOST=true -DBUILTIN_EIGEN=true -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
    - $MAKE install
  # Build the lwtnn example analysis
    - source $INSTALL_PREFIX/rivetenv.sh
    - TEST_PREFIX="$CI_PROJECT_DIR/test_$ARCH"
    - mkdir -p $TEST_PREFIX
    - cd $TEST_PREFIX
    - rivet-build RivetEXAMPLE_LWTNN.so $CI_PROJECT_DIR/analyses/examples/EXAMPLE_LWTNN.cc -llwtnn
    - cp $CI_PROJECT_DIR/analyses/examples/EXAMPLE_LWTNN.json .
  # Run the lwtnn example analysis
    - rivet --pwd -a EXAMPLE_LWTNN $CI_PROJECT_DIR/tt.hepmc.gz
  # For tt.hepmc.gz, there should be only one non-empty histo bin.
    - yodadiff Rivet.yoda $CI_PROJECT_DIR/analyses/valref/EXAMPLE_LWTNN.yoda.gz -t 1e-2
  <<: *trigger_template

check_lwtnn_analyses_ubuntu_gcc_hepmc3_py3:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  needs: [build_ubuntu_gcc_hepmc3_py3, get_test_hepmc]
  <<: *check_lwtnn_analyses_template

check_lwtnn_analyses_ubuntu_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  needs: [build_ubuntu_gcc_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *check_lwtnn_analyses_template

check_lwtnn_analyses_fedora_gcc_hepmc3_py3:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  needs: [build_fedora_gcc_hepmc3_py3, get_test_hepmc]
  <<: *check_lwtnn_analyses_template

check_lwtnn_analyses_fedora_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  needs: [build_fedora_gcc_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - dnf install -y yaml-cpp-devel
  <<: *check_lwtnn_analyses_template

# TODO - Mac version


.check_onnx_analyses_template: &check_onnx_analyses_template
  image: hepstore/hepbase-$ARCH
  stage: check
  script:
  # If we're not in val mode, don't do this test:
    - if [[ $VAL != 1 ]]; then exit 0; fi
  # LWTNN setup variables
    - ONNX_INSTALL_PREFIX="$CI_PROJECT_DIR/local_$ARCH"
    - mkdir -p $ONNX_INSTALL_PREFIX/include/onnxruntime
    - ONNX_VERSION="1.13.1"
  # Download ONNX libs and headers (and move them to share locations)
  # n.b. this command won't work for mac! Will need a new version when we have mac runners.
    - wget https://github.com/microsoft/onnxruntime/releases/download/v$ONNX_VERSION/onnxruntime-linux-x64-$ONNX_VERSION.tgz
    - tar -xf onnxruntime-linux-x64-$ONNX_VERSION.tgz
    - mv onnxruntime-linux-x64-$ONNX_VERSION/lib/*.so* $ONNX_INSTALL_PREFIX/lib
    - mv onnxruntime-linux-x64-$ONNX_VERSION/include/*.h $ONNX_INSTALL_PREFIX/include/onnxruntime
  # Build the onnx example analysis
    - source $ONNX_INSTALL_PREFIX/rivetenv.sh
    - TEST_PREFIX="$CI_PROJECT_DIR/test_$ARCH"
    - mkdir -p $TEST_PREFIX
    - cd $TEST_PREFIX
    - rivet-build RivetEXAMPLE_ONNX.so $CI_PROJECT_DIR/analyses/examples/EXAMPLE_ONNX.cc -lonnxruntime
    - cp $CI_PROJECT_DIR/analyses/examples/EXAMPLE_ONNX.onnx .
  # Run the ONNX example analysis
    - rivet --pwd -a EXAMPLE_ONNX $CI_PROJECT_DIR/tt.hepmc.gz
  # Compare one particularly lively histo bin
    - yodadiff Rivet.yoda $CI_PROJECT_DIR/analyses/valref/EXAMPLE_ONNX.yoda.gz -t 1e-2
  <<: *trigger_template

check_onnx_analyses_ubuntu_gcc_hepmc3_py3:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  needs: [build_ubuntu_gcc_hepmc3_py3, get_test_hepmc]
  <<: *check_onnx_analyses_template

check_onnx_analyses_ubuntu_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: ubuntu-gcc-hepmc3-py3
  needs: [build_ubuntu_gcc_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - apt-get update && apt-get install -y libyaml-cpp-dev
  <<: *check_onnx_analyses_template

check_onnx_analyses_fedora_gcc_hepmc3_py3:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  needs: [build_fedora_gcc_hepmc3_py3, get_test_hepmc]
  <<: *check_onnx_analyses_template

check_onnx_analyses_fedora_gcc_hepmc3_py3_yaml_cpp:
  variables:
    ARCH: fedora-gcc-hepmc3-py3
  needs: [build_fedora_gcc_hepmc3_py3_yaml_cpp, get_test_hepmc]
  before_script:
    - dnf install -y yaml-cpp-devel
  <<: *check_onnx_analyses_template
