ARG BUILD_TOOLS
FROM nohepbase-fedora-$BUILD_TOOLS
LABEL maintainer="rivet-developers@cern.ch"
SHELL ["/bin/bash", "--login", "-c"]

## ROOT
RUN true \
    && dnf install -y libXft libXpm libXext libsqlite3x uuid-devel pcre-devel json-devel xxhash-devel tbb2020.3-devel \
    && dnf clean all \
    && cd /usr/local \
    && wget --no-check-certificate --no-verbose https://root.cern/download/root_v6.32.02.Linux-fedora39-x86_64-gcc13.3.tar.gz -O- | tar xz \
    && echo "source /usr/local/root/bin/thisroot.sh" > /etc/profile.d/10-cernroot.sh

## Most HEP stuff via Rivet bootstrap
# TODO: Add LHAPDF to bootstrap
ARG HEPMC_VERSION
ARG RIVETBS_VERSION
RUN true \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://gitlab.com/hepcedar/rivetbootstrap/-/raw/${RIVETBS_VERSION}/rivet-bootstrap \
    && chmod +x rivet-bootstrap \
    && dnf clean all \
    && PYV=$(python -c "import sys; v = sys.version_info; print(f'{v[0]}.{v[1]}')") \
    && INSTALL_PREFIX=/usr/local USE_VENV=0 \
       INSTALL_RIVET=0 INSTALL_YODA=0 INSTALL_CYTHON=0 \
       INSTALL_HDF5=0 INSTALL_HIGHFIVE=0 \
       HEPMC_VERSION=${HEPMC_VERSION} \
       HEPMC_CMAKE_ADD="-D HEPMC3_Python_SITEARCH${PYV//./}=/usr/local/lib/python$PYV/site-packages -D HEPMC3_PYTHON_VERSIONS=$PYV" \
       MAKE="make -j $(nproc --ignore=1)"  \
       ./rivet-bootstrap \
    && rm -rf /code

## LHAPDF
ARG LHAPDF_VERSION
RUN true \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${LHAPDF_VERSION}.tar.gz -O- | tar xz \
    && cd LHAPDF-*/ \
    && ls wrappers/python/ -l \
    && ./configure --prefix=/usr/local \
    && make -j $(nproc --ignore=1) && make install \
    && ls wrappers/python/build/lhapdf -l \
    && rm -r /code

# ## TeX
# ARG LATEX
# RUN if test "$LATEX" = "1"; then \
#       dnf install -y \
#         texlive texlive-latex \
#         texlive-latex-bin texlive-latexconfig texlive-dvips \
#         texlive-collection-latex texlive-collection-latexrecommended \
#         texlive-pst-tools texlive-pst-arrow \
#         texlive-relsize texlive-cm texlive-hyphen-base \
#         texlive-collection-fontsrecommended texlive-cm-super \
#         ghostscript ImageMagick; \
#       dnf clean all; \
#       texhash; \
#     fi

WORKDIR /work
