ARG UBUNTU_IMAGE=ubuntu:latest #< LTS
FROM ${UBUNTU_IMAGE}
LABEL maintainer="rivet-developers@cern.ch"
SHELL ["/bin/bash", "--login", "-c"]

ARG BUILD_TOOLS
RUN export DEBIAN_FRONTEND=noninteractive \ 
    && apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils tzdata \
    && if [[ "$BUILD_TOOLS" = "gcc" ]]; then \
          CXX_CMD=g++; CC_CMD=gcc; FC_CMD=gfortran; BUILD_PKGS="g++ gcc gfortran"; \
       elif [[ "$BUILD_TOOLS" = "llvm" ]]; then \
          CXX_CMD=clang++; CC_CMD=clang; FC_CMD=gfortran; BUILD_PKGS="clang gfortran"; \
       fi \
    && apt-get install -y ${BUILD_PKGS} \
    && apt-get -y autoremove \
    && apt-get -y autoclean \
    && echo -e "\nexport CXX=$CXX_CMD\nexport CC=$CC_CMD\nexport FC=$FC_CMD\n" >> /etc/profile.d/01-buildtools.sh \
    && cat /etc/profile.d/01-buildtools.sh >> /root/.bashrc

RUN export DEBIAN_FRONTEND=noninteractive \
    && if [[ "$BUILD_TOOLS" = "llvm" ]]; then \
          update-alternatives --install /usr/bin/g++ g++ $(which clang++) 2 && \
          update-alternatives --install /usr/bin/c++ c++ $(which clang++) 2 && \
          update-alternatives --install /usr/bin/gcc gcc $(which clang) 2 && \
          update-alternatives --install /usr/bin/cc  cc  $(which clang) 2; \
          # update-alternatives --install /usr/bin/gfortran gfortran $(which flang) 2; \
       fi \
    && apt-get install -y \
         make automake autoconf libtool cmake rsync \
         git wget tar less bzip2 findutils nano file \
    && apt-get -y autoremove \
    && apt-get -y autoclean

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y python3 python3-dev \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 2 \
    && update-alternatives --install /usr/bin/python-config python-config /usr/bin/python3-config 2 \
    && apt-get -y autoremove \
    && apt-get -y autoclean \
    && apt-get install -y python3-pip && rm -f /usr/lib/python*/EXTERNALLY-MANAGED
    
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update -y \
    && apt-get install -y libxft2 libxpm4 libglu1-mesa libpthread-stubs0-dev libsqlite3-dev uuid-dev nlohmann-json3-dev libtbb-dev \
    && apt-get -y autoclean \
    && cd /usr/local \
    && wget --no-check-certificate --no-verbose https://root.cern/download/root_v6.32.02.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz -O- | tar xz \
    && echo "source /usr/local/root/bin/thisroot.sh" > /etc/profile.d/10-cernroot.sh

# TODO: Update HighFive to 2.9.0... or just let this be handled by the bootstrap
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y zlib1g-dev libgsl-dev libhdf5-dev h5utils hdf5-tools python3-h5py \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://github.com/BlueBrain/HighFive/archive/refs/tags/v2.7.1.tar.gz -O- | tar xz \
    && mv HighFive-*/include/highfive /usr/local/include/ \
    && rm -rf /code \
    && apt-get -y autoremove \
    && apt-get -y autoclean

## Build and enable user content via ld and Python paths
RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "export LD_LIBRARY_PATH=\"/usr/lib64:/usr/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && echo "export LD_LIBRARY_PATH=\"/usr/local/lib64:/usr/local/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && PYV=$(python -c "import sys; v = sys.version_info; print(f'{v[0]}.{v[1]}')") \
    && echo "export PYTHONPATH=\"$(for i in $(ls /usr/local/lib*/python$PYV -d); do echo -n "$i/dist-packages:"; done)\$PYTHONPATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && echo "export PYTHONPATH=\"$(for i in $(ls /usr/local/lib*/python$PYV -d); do echo -n "$i/site-packages:"; done)\$PYTHONPATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && cat /etc/profile.d/05-usrlocal.sh \
    && cp /etc/bash.bashrc /tmp/DUMMY1 \
    && echo 'for i in /etc/profile.d/*.sh; do . $i; done' > /tmp/DUMMY2 \
    && cat /tmp/DUMMY1 /tmp/DUMMY2 > /etc/bash.bashrc && rm /tmp/DUMMY*

# TODO: move libomp-dev requirement back to compilers
# TODO: remove bootstrap hack for HepMC URL
ARG HEPMC_VERSION
ARG RIVETBS_VERSION
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y libomp-dev \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://gitlab.com/hepcedar/rivetbootstrap/raw/${RIVETBS_VERSION}/rivet-bootstrap \
    && sed -e 's!http://hepmc.web.cern.ch/hepmc/releases/!https://cedar-tools.web.cern.ch/downloads/!' -i rivet-bootstrap \
    && chmod +x rivet-bootstrap \
    && apt-get -y autoremove \
    && apt-get -y autoclean \
    && PYV=$(python -c "import sys; v = sys.version_info; print(f'{v[0]}.{v[1]}')") \
    && INSTALL_PREFIX=/usr/local USE_VENV=0 \
       INSTALL_RIVET=0 INSTALL_YODA=0 INSTALL_CYTHON=0 \
       INSTALL_HDF5=0 INSTALL_HIGHFIVE=0 \
       HEPMC_VERSION=${HEPMC_VERSION}  \
       HEPMC_CMAKE_ADD="-D HEPMC3_Python_SITEARCH${PYV//./}=/usr/local/lib/python$PYV/site-packages -D HEPMC3_PYTHON_VERSIONS=$PYV" \
       MAKE="make -j $(nproc --ignore=1)"  \
       ./rivet-bootstrap \
    && rm -rf /code

# TODO: remove /usr/local/local symlink hack once LHAPDF Python is safe from it
ARG LHAPDF_VERSION
RUN export DEBIAN_FRONTEND=noninteractive \
    && mkdir /code && cd /code  \
    && ls -l /usr/local/ \
    && (cd /usr/local && ln -s . local) \
    && ls -l /usr/local/ \
    && wget --no-check-certificate --no-verbose https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${LHAPDF_VERSION}.tar.gz -O- | tar xz \
    && cd LHAPDF-*/ \
    && ls wrappers/python/ -l \
    && ./configure --prefix=/usr/local \
    && make -j $(nproc --ignore=1) && make install \
    && ls wrappers/python/build/lhapdf -l \
    && rm -r /code

# TODO: remove for Rivet v4? Still needed in the mpl for now :-(
ARG LATEX
RUN export DEBIAN_FRONTEND=noninteractive \
    && if test "$LATEX" = "1"; then \
      apt-get update -y && \
      apt-get install -y texlive-latex-recommended texlive-fonts-recommended && \
      apt-get install -y texlive-latex-extra texlive-pstricks cm-super dvipng imagemagick && \
      sed -i 's/^.*policy.*coder.*none.*(PS|PDF).*//' /etc/ImageMagick-6/policy.xml && \
      sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml && \
      texhash && \
      apt-get -y autoremove && \
      apt-get -y autoclean; \      
    fi

# NB. Installing scipy auto-installs a compatible numpy
RUN export DEBIAN_FRONTEND=noninteractive \
    && pip install --upgrade scipy matplotlib Cython requests

## Interactive niceties
ADD bash.bashrc.completion /etc/
RUN export DEBIAN_FRONTEND=noninteractive \
    && cat /etc/bash.bashrc.completion >> /etc/bash.bashrc \
    && rm /etc/bash.bashrc.completion

WORKDIR /work
