ARG BUILD_TOOLS
FROM nohepbase-ubuntu-$BUILD_TOOLS
LABEL maintainer="rivet-developers@cern.ch"
SHELL ["/bin/bash", "--login", "-c"]

## ROOT
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update -y \
    && apt-get install -y libxft2 libxpm4 libglu1-mesa libpthread-stubs0-dev libsqlite3-dev uuid-dev nlohmann-json3-dev libtbb-dev \
    && apt-get -y autoclean \
    && cd /usr/local \
    && wget --no-check-certificate --no-verbose https://root.cern/download/root_v6.32.08.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz -O- | tar xz \
    && echo "source /usr/local/root/bin/thisroot.sh" > /etc/profile.d/10-cernroot.sh

## Most HEP stuff via Rivet bootstrap
# TODO: Add LHAPDF to bootstrap
ARG HEPMC_VERSION
ARG RIVETBS_VERSION
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y  \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://gitlab.com/hepcedar/rivetbootstrap/-/raw/${RIVETBS_VERSION}/rivet-bootstrap \
    && chmod +x rivet-bootstrap \
    && apt-get -y autoremove \
    && apt-get -y autoclean \
    && PYV=$(python -c "import sys; v = sys.version_info; print(f'{v[0]}.{v[1]}')") \
    && INSTALL_PREFIX=/usr/local USE_VENV=0 \
       INSTALL_RIVET=0 INSTALL_YODA=0 INSTALL_CYTHON=0 \
       INSTALL_HDF5=0 INSTALL_HIGHFIVE=0 \
       HEPMC_VERSION=${HEPMC_VERSION}  \
       HEPMC_CMAKE_ADD="-D HEPMC3_Python_SITEARCH${PYV//./}=/usr/local/lib/python$PYV/site-packages -D HEPMC3_PYTHON_VERSIONS=$PYV" \
       MAKE="make -j $(nproc --ignore=1)"  \
       ./rivet-bootstrap \
    && rm -rf /code

## LHAPDF
# TODO: remove /usr/local/local symlink hack once LHAPDF Python is safe from it
ARG LHAPDF_VERSION
RUN export DEBIAN_FRONTEND=noninteractive \
    && mkdir /code && cd /code  \
    && ls -l /usr/local/ \
    && (cd /usr/local && ln -s . local) \
    && ls -l /usr/local/ \
    && wget --no-check-certificate --no-verbose https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${LHAPDF_VERSION}.tar.gz -O- | tar xz \
    && cd LHAPDF-*/ \
    && ls wrappers/python/ -l \
    && ./configure --prefix=/usr/local \
    && make -j $(nproc --ignore=1) && make install \
    && ls wrappers/python/build/lhapdf -l \
    && rm -r /code

# ## TeX
# ARG LATEX
# RUN export DEBIAN_FRONTEND=noninteractive \
#     && if test "$LATEX" = "1"; then \
#       apt-get update -y && \
#       apt-get install -y texlive-latex-recommended texlive-fonts-recommended && \
#       apt-get install -y texlive-latex-extra texlive-pstricks cm-super dvipng imagemagick && \
#       sed -i 's/^.*policy.*coder.*none.*(PS|PDF).*//' /etc/ImageMagick-6/policy.xml && \
#       sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml && \
#       texhash && \
#       apt-get -y autoremove && \
#       apt-get -y autoclean; \      
#     fi

WORKDIR /work
