#! /usr/bin/env bash

for t in $(git tag | grep -v "alpha" | grep -v "chacal" | sort -r -V); do
    epoch=$(git show -s -n 1 --format=%at $t)
    nanas=$(git ls-tree --full-tree -r --name-only $t src/Analyses/ src/Analysis/ analyses | grep '\.cc' | wc -w)
    echo "$t $epoch $nanas"
done
