ARG UBUNTU_IMAGE=ubuntu:latest #< LTS
FROM ${UBUNTU_IMAGE}
LABEL maintainer="rivet-developers@cern.ch"
SHELL ["/bin/bash", "--login", "-c"]

## Build tools
ARG BUILD_TOOLS
RUN export DEBIAN_FRONTEND=noninteractive \ 
    && apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils tzdata libomp-dev \
    && if [[ "$BUILD_TOOLS" = "gcc" ]]; then \
          CXX_CMD=g++; CC_CMD=gcc; FC_CMD=gfortran; BUILD_PKGS="g++ gcc gfortran"; \
       elif [[ "$BUILD_TOOLS" = "llvm" ]]; then \
          CXX_CMD=clang++; CC_CMD=clang; FC_CMD=gfortran; BUILD_PKGS="clang gfortran"; \
       fi \
    && apt-get install -y ${BUILD_PKGS} \
    && apt-get -y autoremove \
    && apt-get -y autoclean \
    && echo -e "\nexport CXX=$CXX_CMD\nexport CC=$CC_CMD\nexport FC=$FC_CMD\n" >> /etc/profile.d/01-buildtools.sh \
    && cat /etc/profile.d/01-buildtools.sh >> /root/.bashrc

## Build-tool aliases
RUN export DEBIAN_FRONTEND=noninteractive \
    && if [[ "$BUILD_TOOLS" = "llvm" ]]; then \
          update-alternatives --install /usr/bin/g++ g++ $(which clang++) 2; \
          update-alternatives --install /usr/bin/c++ c++ $(which clang++) 2; \
          update-alternatives --install /usr/bin/gcc gcc $(which clang) 2; \
          update-alternatives --install /usr/bin/cc  cc  $(which clang) 2; \
          #which flang && update-alternatives --install /usr/bin/gfortran gfortran $(which flang) 2 || true; \
       fi \
    && apt-get install -y \
         make automake autoconf libtool cmake rsync \
         git wget tar less bzip2 findutils nano file \
    && apt-get -y autoremove \
    && apt-get -y autoclean

## Python
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y python3 python3-dev \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 2 \
    && update-alternatives --install /usr/bin/python-config python-config /usr/bin/python3-config 2 \
    && apt-get -y autoremove \
    && apt-get -y autoclean \
    && apt-get install -y python3-pip && rm -f /usr/lib/python*/EXTERNALLY-MANAGED \
    && pip install scipy matplotlib requests Cython
# NB. Installing scipy auto-installs a compatible numpy

## Build and enable user content via ld and Python paths
RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "export LD_LIBRARY_PATH=\"/usr/lib64:/usr/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && echo "export LD_LIBRARY_PATH=\"/usr/local/lib64:/usr/local/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && PYV=$(python -c "import sys; v = sys.version_info; print(f'{v[0]}.{v[1]}')") \
    && echo "export PYTHONPATH=\"$(for i in $(ls /usr/local/lib*/python$PYV -d); do echo -n "$i/dist-packages:"; done)\$PYTHONPATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && echo "export PYTHONPATH=\"$(for i in $(ls /usr/local/lib*/python$PYV -d); do echo -n "$i/site-packages:"; done)\$PYTHONPATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && cat /etc/profile.d/05-usrlocal.sh \
    && cp /etc/bash.bashrc /tmp/DUMMY1 \
    && echo 'for i in /etc/profile.d/*.sh; do . $i; done' > /tmp/DUMMY2 \
    && cat /tmp/DUMMY1 /tmp/DUMMY2 > /etc/bash.bashrc && rm /tmp/DUMMY*

## HDF5
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y zlib1g-dev libgsl-dev libhdf5-dev h5utils hdf5-tools python3-h5py \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://github.com/BlueBrain/HighFive/archive/refs/tags/v2.10.1.tar.gz -O- | tar xz \
    && mv HighFive-*/include/highfive /usr/local/include/ \
    && rm -rf /code \
    && apt-get -y autoremove \
    && apt-get -y autoclean

## Interactive niceties
ADD bash.bashrc.completion /etc/
RUN export DEBIAN_FRONTEND=noninteractive \
    && cat /etc/bash.bashrc.completion >> /etc/bash.bashrc \
    && rm /etc/bash.bashrc.completion

## TeX
ARG LATEX
RUN export DEBIAN_FRONTEND=noninteractive \
    && if test "$LATEX" = "1"; then \
      apt-get update -y && \
      apt-get install -y texlive-latex-recommended texlive-fonts-recommended && \
      apt-get install -y texlive-latex-extra texlive-pstricks cm-super dvipng imagemagick && \
      sed -i 's/^.*policy.*coder.*none.*(PS|PDF).*//' /etc/ImageMagick-6/policy.xml && \
      sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml && \
      texhash && \
      apt-get -y autoremove && \
      apt-get -y autoclean; \      
    fi
