ARG FEDORA_IMAGE=fedora:latest  #< stable
FROM ${FEDORA_IMAGE}
LABEL maintainer="rivet-developers@cern.ch"
SHELL ["/bin/bash", "--login", "-c"]

## Build tools
ARG BUILD_TOOLS
RUN true \
    && dnf update -y \
    && dnf upgrade -y \
    && if [[ "$BUILD_TOOLS" = "gcc" ]]; then \
          CXX_CMD=g++; CC_CMD=gcc; FC_CMD=gfortran; BUILD_PKGS="gcc gcc-c++ gcc-gfortran"; \
       elif [[ "$BUILD_TOOLS" = "llvm" ]]; then \
          CXX_CMD=clang++; CC_CMD=clang; FC_CMD=flang; BUILD_PKGS="clang gcc-gfortran"; \
       else \
          echo "Unknown BUILD_TOOLS option '$BUILD_TOOLS'"; \
       fi \
    && dnf install -y ${BUILD_PKGS} \
    && dnf clean all \
    && echo -e "\nexport CXX=$CXX_CMD\nexport CC=$CC_CMD\nexport FC=$FC_CMD\n" >> /etc/profile.d/01-buildtools.sh \
    && cat /etc/profile.d/01-buildtools.sh >> /root/.bashrc

## Build-tool aliases
RUN true \
    && if [[ "$BUILD_TOOLS" = "llvm" ]]; then \
          update-alternatives --install /usr/bin/g++ g++ $(which clang++) 2; \
          update-alternatives --install /usr/bin/c++ c++ $(which clang++) 2; \
          update-alternatives --install /usr/bin/gcc gcc $(which clang) 2; \
          update-alternatives --install /usr/bin/cc  cc  $(which clang) 2; \
          update-alternatives --install /usr/bin/gfortran gfortran $(which gfortran) 2; \
          fi \
    && dnf install -y \
         make redhat-rpm-config cmake \
         m4 automake autoconf libtool \
         git wget tar less bzip2 findutils which nano file diffutils \
    && dnf clean all

## Python
RUN true \
    && dnf install -y python3 python3-devel \
    && alternatives --install /usr/bin/python python /usr/bin/python3 2 \
    && alternatives --install /usr/bin/python-config python-config /usr/bin/python3-config 2 \
    && dnf clean all \
    && pip install scipy matplotlib requests Cython
# NB. Installing scipy auto-installs a compatible numpy

## Build and enable user content via ld and Python paths
RUN true \
    && echo "export LD_LIBRARY_PATH=\"/usr/lib64:/usr/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && echo "export LD_LIBRARY_PATH=\"/usr/local/lib64:/usr/local/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && PYV=$(python -c "import sys; v = sys.version_info; print(f'{v[0]}.{v[1]}')") \
    && echo "export PYTHONPATH=\"$(for i in $(ls /usr/local/lib*/python$PYV -d); do echo -n "$i/dist-packages:"; done)\$PYTHONPATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && echo "export PYTHONPATH=\"$(for i in $(ls /usr/local/lib*/python$PYV -d); do echo -n "$i/site-packages:"; done)\$PYTHONPATH\"" >> /etc/profile.d/05-usrlocal.sh \
    && cat /etc/profile.d/05-usrlocal.sh \
    && cp /etc/bashrc /tmp/DUMMY1 \
    && echo 'for i in /etc/profile.d/*.sh; do . $i; done' > /tmp/DUMMY2 \
    && cat /tmp/DUMMY1 /tmp/DUMMY2 > /etc/bashrc && rm /tmp/DUMMY*

## HDF5
RUN true \
    && dnf install -y zlib-devel gsl-devel hdf5-devel python3-h5py \
    && dnf clean all \
    && mkdir /code && cd /code \
    && wget --no-check-certificate --no-verbose https://github.com/BlueBrain/HighFive/archive/refs/tags/v2.10.1.tar.gz -O- | tar xz \
    && mv HighFive-*/include/highfive /usr/local/include/ \
    && rm -rf /code

## Interactive niceties
ADD bash.bashrc.completion /etc/
RUN true \
    && cat /etc/bash.bashrc.completion >> /etc/bashrc \
    && rm /etc/bash.bashrc.completion \
    && echo "alias ll='ls -l'" > /etc/profile.d/15-aliases.sh

## TeX
ARG LATEX
RUN if test "$LATEX" = "1"; then \
      dnf install -y \
        texlive texlive-latex \
        texlive-latex-bin texlive-latexconfig texlive-dvips \
        texlive-collection-latex texlive-collection-latexrecommended \
        texlive-pst-tools texlive-pst-arrow \
        texlive-relsize texlive-cm texlive-hyphen-base \
        texlive-collection-fontsrecommended texlive-cm-super \
        ghostscript ImageMagick; \
      dnf clean all; \
      texhash; \
    fi
