ARG BUILD_TOOLS
FROM hepstore/hepbase-fedora-$BUILD_TOOLS
LABEL maintainer="rivet-developers@cern.ch"
SHELL ["/bin/bash", "--login", "-c"]

## TeX
ARG LATEX
RUN if test "$LATEX" = "1"; then \
      dnf install -y \
        texlive texlive-latex \
        texlive-latex-bin texlive-latexconfig texlive-dvips \
        texlive-collection-latex texlive-collection-latexrecommended \
        texlive-pst-tools texlive-pst-arrow \
        texlive-relsize texlive-cm texlive-hyphen-base \
        texlive-collection-fontsrecommended texlive-cm-super \
        ghostscript ImageMagick; \
      dnf clean all; \
      texhash; \
    fi

WORKDIR /work
